name: Merge to master branch

on:
  push:
    branches: master

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -i 's/ -i http:\/\/mirrors.aliyun.com\/pypi\/simple\/ --extra-index-url https:\/\/pypi.python.org\/simple --trusted-host mirrors.aliyun.com/ /g' Dockerfile
      - run: sed -i 's/ -i http:\/\/mirrors.aliyun.com\/pypi\/simple\/ --extra-index-url https:\/\/pypi.python.org\/simple --trusted-host mirrors.aliyun.com/ /g' docker-compose.test.yml
      - run: make build && make test
