name: Merge to main branch

on:
  push:
    branches: main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -i 's/ -i http:\/\/mirrors.aliyun.com\/pypi\/simple --extra-index-url https:\/\/pypi.douban.com\/simple --trusted-host mirrors.aliyun.com/ /g' Dockerfile
      - run: sed -i 's/ -i http:\/\/mirrors.aliyun.com\/pypi\/simple --extra-index-url https:\/\/pypi.douban.com\/simple --trusted-host mirrors.aliyun.com/ /g' docker-compose.test.yml
      - run: make build && make test

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml,bot/coverage.xml
            -Dsonar.tests=utils/,bot/
            -Dsonar.verbose=true
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
